server:
  port: 8080

spring:
  application:
    name: Auth-Service

jwt:
  secret: ${JWT_SECRET}

app:
  password-reset:
    token-expiry-hours: 1
    prevent-reuse: true


#logging:
#  level:
#    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      access: NONE


springdoc:
  swagger-ui:
    enabled: false

