spring:

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable:
          idempotence: false
        max:
          block:
            ms: 5000
        request:
          timeout:
            ms: 5000

    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            trusted:
              packages: "*"


  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    schemas: public

  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

    exchanges:
      emailVerification: x.email.verification
#      emailSignup: x.signup
#      emailPasswordReset: x.password-reset
#      profileUpdate: x.update-profile
#      accountDeactivation: x.account-deactivation
    queues:
      emailVerification: q.users.email
#      emailSignup: q.email.signup
#      emailPasswordReset: q.password.reset
#      profileUpdate: q.update.profile
#      accountDeactivation: q.account.deactivate
    routing-keys:
      emailVerification: EmailVerificationEvent
#      emailSignup: SendEmailVerificationLinkEvent
#      emailPasswordReset: user.password.reset
#      profileUpdate: user.profile.update
#      accountDeactivation: user.account.deactivate


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      access: UNRESTRICTED

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    web: debug
    root: info

    org:
      springframework:
        security:
          config:
            annotation:
              authentication:
                configuration:
                  InitializeUserDetailsBeanManagerConfigurer: ERROR
      hibernate:
        SQL: DEBUG


        orm:
          jdbc:
            bind: trace

kafka:
    topics:
      email-verification: email-verification-topic
      otp-verification: otp-verification-topic
      password-reset: password-reset-topic
      welcome-email: welcome-email-topic

    groups:
      email-verification: group-email-verification
      otp-verification: group-otp-verification
      password-reset: group-password-reset
      welcome-email: group-welcome-email

resend:
  api-key: ${RESEND_API_KEY}
  from: onboarding@resend.dev